Training:   0%|          | 0/75 [00:00<?, ?it/s]
  0%|          | 0/449 [00:00<?, ?it/s][A
                                       [ATraining:   0%|          | 0/75 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/gscratch/stf/lbc800/fashion-app/train_attribute_detector.py", line 193, in <module>
    torch.save(train_model(model, train_loader, val_loader, optimizer, device, criterion),'Fefficientnet.pth')
  File "/gscratch/stf/lbc800/fashion-app/train_attribute_detector.py", line 92, in train_model
    for images, labels in tqdm(data_loader, leave = False):
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 708, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1480, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1505, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 733, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 349, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/gscratch/stf/lbc800/fashion-app/train_attribute_detector.py", line 30, in __getitem__
    image = Image.open(image_path).convert("RGB")
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 3505, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'imat_data/img26006.jpg'

